### ISSUE TITLE
Create `Account::from_secret_key()` and a way to change sign key for an `Account`

### ISSUE THREAD

**Issue by Buckram123** [near/workspaces-rs#128]
Should be useful for testing added keys, for example:
 `contract_a` creates a key for himself but now we need a way to sign it with this key.
 It can be done using `Account::from_file()`, but I feel like there must be a lazier way like `Account::from_secret_key()`, or `contract_a.change_key(sk)`. Correct me if im missing anything, ready to implement it too.

**Comment by ChaoticTempest** [comment]
There's an `Account::new()` function that does exactly what you'd want from `Account::from_secret_key` except it takes in an `InMemorySigner` instead and isn't publicly exposed. But feel free to add a new `Account::from_secret_key` that is more ergonomic, probably with the sig `fn from_secret_key(AccountId, SecretKey)`. 

Updating the secret key can be a little bit tricky, since `Account` is directly associated to one on chain. So updating those keys would have to be a must as well

Let me know if you need anything if you want to implement it

**Comment by Buckram123** [comment]
@ChaoticTempest should `Account::new()` just be public then?

**Comment by ChaoticTempest** [comment]
yup if it has a use, but should be more explicitly named than just `new`

**Comment by Buckram123** [comment]
Is it ok to create testing example on multisig contract or take something simpler?

**Comment by ChaoticTempest** [comment]
Multisig is a pretty big contract. If its not too complicated, can you just create a new minimized multisig contract with just the methods you're using in the testing

**Comment by Buckram123** [comment]
That's a great idea, thanks

**Comment by ChaoticTempest** [comment]
closed with https://github.com/near/workspaces-rs/pull/185
