### ISSUE TITLE
feature flag no_sandbox

### ISSUE THREAD

**Issue by ChzenChzen** [near/workspaces-rs#155]
Is it possible to add this feature flag for the crate? I have an M1 Mac and must switch the project toolchain to x86-64 to solve the issue with the compilation of the workspaces-rs. But I am still unable to use the Sandbox functionality. Also, It breaks my IDE functionality (JetBrains rust plugin fails to expand macros). I would like to have an aarch64 toolchain and don't use the Sandbox.

**Comment by itegulov** [comment]
I feel your pain, but my understanding is that M1 support for sandbox is coming very soon. @ChaoticTempest do we need anything else after https://github.com/near/nearcore/issues/6281 (wasmtime upgrade) was fixed?

**Comment by ChzenChzen** [comment]
@itegulov, what does "very soon" mean? Is it a week, month, or more?

**Comment by itegulov** [comment]
My understanding is that the wasmtime upgrade was not included in the recent nearcore 1.27.0 release, so we need to wait for the first 1.28.0 release. We could probably use release candidates for sandbox purposes and I am assuming rc.1 is going to come out in a couple of weeks at most. In the meantime, we should confirm that M1 support works as intended. That being said, @ChaoticTempest probably has more context here than I do, so feel free to correct me.

**Comment by ChaoticTempest** [comment]
M1 should be available to use, albeit in a roundabout way since we don't have binaries published yet. We're building out the pipeline right now and should make it in within a month at the worst. Most of the pipeline is done and is in testing, but otherwise if you'd like to make use of M1 workspaces right now, you can go with the roundabout way as a temporary solution:
1. compile nearcore on your M1 macbook via `cd nearcore && make sandbox-release`
2. goto your project repo, then to run the tests, execute `NEAR_SANDBOX_BIN_PATH=/absolute/path/to/nearcore/sandbox/release/neard cargo test`

**Comment by ChzenChzen** [comment]
@ChaoticTempest I've done as you said, but I've got an error:

```
error: Unsupported platform
  --> /Users/fomotoshi/.cargo/registry/src/github.com-1ecc6299db9ec823/near-sandbox-utils-0.2.0/src/lib.rs:24:5
   |
24 |     compile_error!("Unsupported platform");
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


error[E0308]: mismatched types
  --> /Users/fomotoshi/.cargo/registry/src/github.com-1ecc6299db9ec823/near-sandbox-utils-0.2.0/src/lib.rs:13:24
   |
13 | const fn platform() -> &'static str {
   |          --------      ^^^^^^^^^^^^ expected `&str`, found `()`
   |          |
   |          implicitly returns `()` as its body has no tail or `return` expression


```
