### ISSUE TITLE
Near dependency crates inconsist with workspace

### ISSUE THREAD

**Issue by yanganto** [near/workspaces-rs#171]
Hi,
I am new to NEAR and run into an issue with `near-sdk` and `workspace` with the following problem
```text
Error: No such file or directory (os error 2)
thread 'round_trip' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: the test returned a termination value with a non-zero status code (1) which indicates a failure', /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/test/src/lib.rs:185:5
```

I am not sure the following dependency issue cause on this, but the near dependency crates are inconsistent between `workspace` and `near-sdk`.

```toml
[package]
name = "near-sdk"
version = "4.0.0"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
near-vm-logic = "0.13"
near-primitives-core = "0.13"
near-primitives = "0.13"
near-crypto = "0.13"
```

```toml
[package]
name = "workspaces"
version = "0.4.0"

[dependencies]
near-account-id = "0.14.0"
near-crypto = "0.14.0"
near-primitives = "0.14.0"
```

If this is not an issue, could you kindly show me how to select a workable match on the version `workspaces` and the version of `near-sdk`. 
Thanks in advanced.  :pray:

**Comment by ChaoticTempest** [comment]
this one was out of our control for updating the dependencies since `near-jsonrpc-client-rs` are coupled to the newest versions. Probably ideal to update both at the same time when making updates to workspaces-rs though, but not sure what is causing this failure since `workspaces` tests utilizes near-sdk-rs 4.0 but doesn't run into any issues.

> Error: No such file or directory (os error 2)

@yanganto This error message makes me think you're running into the latest workspaces API changes such as `Account::from_file` returning an error now, but I could be wrong. Let me know if you can share the actual test so we can we see what's going on

**Comment by yanganto** [comment]
Hi @ChaoticTempest, I try to connect with the owner of a current private project, and he will let you access and check the test case.  Please kindly notice the invitation.  Thanks.

**Comment by yanganto** [comment]
Thanks. This only happens locally, and it is possibly more related to the developing environment.
