### ISSUE TITLE
Disambiguate RPC statuses and transaction statuses

### ISSUE THREAD

**Issue by austinabell** [near/workspaces-rs#183]
This issue is more for discussion, as it's not so clear what the API should end up being. The issue now is that there are a few execution statuses [that cannot be hit with current code paths](https://github.com/near/workspaces-rs/blob/d4768f9cfae2569f7d78fcfb7e1cb4f8e61bb14e/workspaces/src/result.rs#L94-L99) because it represents transactions that have not finalized, and the workspaces transaction API ensures that the transaction is finalized (afaik -- correct me if I'm wrong), and it can lead to an unintuitive API. 

Intuitively, it seems like the result from RPC should be expressed as follows (roughly):

```rust
enum CallExecutionResult {
  NotStarted,
  Started(/* contains data around how much gas is used so far, receipts that have been finalized */)
  Success(CallExecutionSuccess),
  Failure(CallExecutionFailure),
}

struct CallExecutionSuccess {
  success_value: String
  total_gas_burnt: Gas,
  outcome: ExecutionOutcome, // Pointing to current type, but likely this would follow the same pattern
  receipts: Vec<ExecutionOutcome>,
}

struct CallExecutionFailure {
  error: TxExecutionError,
  total_gas_burnt: Gas,
  outcome: ExecutionOutcome, // Pointing to current type, but likely this would follow the same pattern
  receipts: Vec<ExecutionOutcome>,
}
```

Where the transaction function would return `Result<CallExecutionSuccess, CallExecutionFailure>` since we are sure by the API that the transaction has finalized. For the use of just querying a transaction that we submitted async and did not wait on, the API would return `CallExecutionResult` and then the user would be able to check what the status is or assert things themselves.

I'm leaving some details out, but can clarify in more detail my reasoning if unclear.

**Comment by ChaoticTempest** [comment]
> Where the transaction function would return Result<CallExecutionSuccess, CallExecutionFailure> [...]

you're saying we can just use the `transact()` function to return this instead of returning `CallExecutionDetails` right? This would avoid the `#[must_use]` but in this case, the error type being CallExecutionFailure would make it inconsistent with the Error type. hmm, actually, it could be a concrete error type where we can have a `From<CallExecutionFailure> for workspaces::Error` impl if the user wants to convert it a `workspaces::Error` type. So not too bad in that case.

I get that matching the `Error` to an execution then to get the details is a bit much, but how about we have something like 

>  [...] we are sure by the API that the transaction has finalized. For the use of just querying a transaction that we submitted async and did not wait on, the API would return CallExecutionResult and then the user would be able to check what the status is or assert things themselves

This is true, currently workspaces-rs doesn't have a `transact_async` and `transact_status` which should be added in a future PR.

Overall, this sounds reasonable

**Comment by ChaoticTempest** [comment]
actually, forgot about this one additional detail, but we can't exactly have the signature of `transact() ->  Result<CallExecutionSuccess, CallExecutionFailure>` because the Error type is not just execution related error, but also RPC as well. So I don't think we can avoid the case where we have to hide these details underneath `Error` itself

**Comment by ChaoticTempest** [comment]
> How about having something like:
> 
> ```rust
> transact() -> Result<CallExecutionResult, workspaces::error::Error>;
> 
> struct CallExecutionResult(Result<CallExecutionSuccess, CallExecutionFailure>);
> 
> impl CallExecutionResult {
>   ...
> 
>   fn into_result() -> Result<CallExecutionSuccess, CallExecutionFailure> { ... }
> }
> ```
> 
> Which has a similar pattern to what exists now, and we can have the same types, just the Error when converting into a result is actually usable, and it might be easier to maintain in the future? Again, just proposing new options for consideration

In that case, we'd still have to have `#[must_use]` to force the users to handle the `CallExecutionResult` but that's not too big of a deal, just that it's gonna be another breaking change 😅. https://github.com/near/workspaces-rs/pull/150 was already willing to accept that breaking change though, so no surprise there
