### ISSUE TITLE
binary near-sandbox does not exist

### ISSUE THREAD

**Issue by mrLSD** [near/workspaces-rs#193]
For some reason when I run the tests I get the error
```
binary near-sandbox does not exist
```

Tests run on Github actions.

Error action example:
https://github.com/aurora-is-near/aurora-eth-connector/actions/runs/3051620462/jobs/4920243971

However, the tests ran successfully before:
https://github.com/aurora-is-near/aurora-eth-connector/actions/runs/2975668461/jobs/4767647587

**Comment by ChaoticTempest** [comment]
This is quite strange behavior. The binary gets installed during build-time of `workspaces-rs`, so we should have it for all tests by the time it gets ran. Let me investigate further what's going on specifically for your guy's tests

**Comment by strokovok** [comment]
In our case, the order is for some reason the opposite:
```
...
Error: binary /root/runners_workdir/runners/Aurora-GH-runner-2/aurora-eth-connector/aurora-eth-connector/target/debug/build/near-sandbox-utils-aa5631c088eefc9c/out/near-sandbox does not exist
...
Installed near-sandbox into /root/runners_workdir/runners/Aurora-GH-runner-2/aurora-eth-connector/aurora-eth-connector/target/debug/build/near-sandbox-utils-aa5631c088eefc9c/out/near-sandbox
...
```
So it looks like it's first accessed and not found, and only then it's built. Can it be some sort of race?

Also, can we maybe force build it _before_ running tests?

**Comment by ChaoticTempest** [comment]
So I found out why you guys are running into the issue. I didn't know that cargo could end up using two different `near-sandbox-utils` crate underneath (if specified for both `dependencies` and `build-dependencies`) which ends up causing this race condition due to `workspaces-rs` using `near-sandbox-utils` in `build.rs` to pre-install the binary (one installs the binary during build time, while a completely different one gets used during testing time). I'm surprised I haven't ran into this issue earlier, but for some reason, your guys cargo builds are more special and just ends up having cargo resolve `near-sandbox-utils` to be two separate dependencies in `target/debug/build/` instead of the usual one.

`near-sandbox-utils` originally does not handle the case of installing the binaries concurrently very well, so the solution I came up with here in https://github.com/near/sandbox/pull/50 is to have it resolve concurrently installing with a lockfile while at test-time, just so we don't have to worry about pre-installs if cargo decides to have two separate crates for `near-sandbox-utils`

**Comment by mrLSD** [comment]
@ChaoticTempest please give me instructions on what I should do, to fix my tests after that https://github.com/near/sandbox/pull/50 update?
I tried to re-run CI, and it doesn't help:
https://github.com/aurora-is-near/aurora-eth-connector/actions/runs/3182270492/jobs/5188000550

**Comment by ChaoticTempest** [comment]
ahh, this is not completed yet. The issue has been resolved on sandbox side, but it needs to be pulled into workspaces as well. GH auto marked as completed, but let me reopen till this gets patched on workspaces side.
