### ISSUE TITLE
Ability to create Workspace errors

### ISSUE THREAD

**Issue by joshuajbouw** [near/workspaces-rs#194]
We aim to build a wrapper around the `Contract` struct for the Aurora EVM. What would be a nice feature is if we can create our own workspace `Error`s, specifically the `ErrorRepr::Simple`, `ErrorRepr::Message`, and `ErrorRepr::Custom`. The benefit of this is that those that use our EVM wrapper will be able to have the ability also to use the same `Error`s as `Workspace`. 

I don't see why anyone would ever need access to the more detailed errors which include `ExecutionFailure`, as those should only come from the execution itself.

### More than one error type (more work, best solution)

The errors could be split into more specific error returns depending on the context. For example, one each for data conversion errors, rpc, execution, sandbox, and IO.

### Remove `pub(crate)` in some cases (less work)

The `pub(crate)` could be removed such as in `Error::custom`, `Error::message`, and `Error::simple`.

**Comment by ChaoticTempest** [comment]
> The errors could be split into more specific error returns depending on the context. For example, one each for data conversion errors, rpc, execution, sandbox, and IO.

Originally was split into their own specific errors, but had a lot of maintenance burden with not much real value add, since at the end of the day, errors were getting merged into the higher level `workspaces::Error` object anyways. So it's much simpler to have this one singular `Error` type where we can internally just scale the `ErrorKind` vairants without much further work

**Comment by ChaoticTempest** [comment]
resolved with latest 0.7.0 version
