### ISSUE TITLE
Mac M1 AVX problem with workspaces 0.6.0

### ISSUE THREAD

**Issue by mercepluka** [near/workspaces-rs#233]
I am experiencing a problem when running tests on Mac M1 with following setup:
- rustup version is 1.25.1 (installed with `brew install rustup`
- rustc version is 1.64 (installed with `rustup install 1.64`)
- used `rustup target add wasm32-unknown-unknown`
- workspace version is set to 0.6.0

I ran build script:
```
#!/bin/bash

cargo build --target wasm32-unknown-unknown --release
cp target/wasm32-unknown-unknown/release/prover.wasm ../wasm/

``` 

Build script executes without warnings or errors and after that I do `cargo test`, and as a part of the result of the test I have:

`status: Failure(ActionError(ActionError { index: Some(0), kind: FunctionCallError(CompilationError(WasmerCompileError { msg: "The target x86_64 without AVX is not yet supported (see https://docs.wasmer.io/ecosystem/wasmer/wasmer-features)" }
`

Same code when built and tested on older (Intel) Mac passes all of the tests. Is there any known solution for this?

**Comment by ChaoticTempest** [comment]
That error should only happen when your rust toolchain is targeting darwin-x86 when you're on a M1/arm machine. `rustup default` should show it. It's best if you can switch to the native M1 target: `rustup default stable-aarch64-apple-darwin`.

Also, just making sure, but did you put `workspaces` in `[dependencies]` or `[dev-dependencies]`of `Cargo.toml`? If it's in `[dependencies]`, it's going to fail later after you switch the rust toolchain, due to workspaces not being compilable to wasm with the build command `cargo build --target wasm32-unknown-unknown --release`. So best to put it in `[dev-dependencies]` if you haven't done so

**Comment by mercepluka** [comment]
Thank you for the help. Just to point out that `rustup default stable-aarch64-apple-darwin` did not solve my problem out of the box, but it was the step in the correct direction.

For some reason when I used `rustup show` in my folder there was a message that stated that aarch64 is default, but that for that folder uses x86 because of the override. This was solved by using `rustup override set stable-aarch64-apple-darwin`, after that `stable-aarch64-apple-darwin` was set for all folders and my `build` and `cargo test` worked.
