### ISSUE TITLE
Investigate inner JSON RPC serialization

### ISSUE THREAD

**Issue by ChaoticTempest** [near/workspaces-rs#36]
Currently, default args supplied to calling into a contract change function is an empty json map `{}`. This is required when we want to supply no arguments to a change function that take all `Option`als. This might just be a weird case in how jsonrpc is interpreting/serializing the bytes underneath.

Additionally, functions that take no arguments are fine with either empty bytes (`Vec::new()`) or the empty json map (`json!({})`).

We'll need to take a look closer to see whether this is the right thing to be using or not. But for now, `json({})` will be the default.

Original discussion of this here: https://github.com/near/workspaces-rs/pull/33#discussion_r768266227_

**Comment by itegulov** [comment]
I did a little investigation and this is what I found out: functions that take no argument accept literally any byte array as a valid argument payload because they don't try to deserialize it. So it is just a coincidence that an empty byte array works for them. Functions that have all parameters as `Option`als do try to deserialize the payload and they expect a valid JSON struct there (e.g. `{}` is a valid a struct while an empty byte array or an empty string isn't). So my conclusion is that supplying `{}` by default is the correct behaviour.

@ChaoticTempest lmk if you need me to look into this any further

**Comment by ChaoticTempest** [comment]
Oh cool. One question then, would this be the same with `borsh` as well? It's just one of the things I haven't gotten around to testing yet: if just a pure json `{}` is valid, since for borsh (de)serialized parameters, we'd be supplying this default as well

**Comment by itegulov** [comment]
Borsh works the same way for parameterless functions (i.e. deserialization is not being run, which actually makes me think maybe we should make it check that the payload is empty?). For functions that have all parameters as `Option`als we have to pass `[0, 0, ..., 0]` where the number of zeros is equal to the number of parameters. So passing `{}` does not work for borsh-powered functions and I don't think there is a way to come up with a general default argument without knowing which serialization the function uses and the number of its parameters. I think for the sake of consistency we should just pass an empty byte array by default so that only parameterless function would be covered and once we develop ACI for contracts we can revisit this topic.

**Comment by itegulov** [comment]
@ChaoticTempest if I understood you correctly during our meeting today you were wondering how near-cli does it so I looked into it and they also just pass `{}` by default: https://github.com/near/near-cli/blob/deeba1cd19188bcab0003baa21da1dc00a80a156/commands/call.js#L54. Generally it seems like they only support json serialization so it makes sense.

**Comment by ChaoticTempest** [comment]
@itegulov so think its best then to just default to empty bytes. This will be a bit difficult to spot on the user side since this is not a very intuitive error to understand when we're supply empty bytes but its trying deserialize for optionals: `"Smart contract panicked: panicked at 'Failed to deserialize input from JSON.: Error(\"EOF while parsing a value\"`. 

We can try to filter out for certain errors then map them to more intuitive errors later on, but for this ticket, let's just set the default to empty bytes and then creating corresponding tickets to address dealing with more intuitive user errors later. I also added https://github.com/near/workspaces-rs/pull/83 which propagates these errors a little better than just being ignored

**Comment by itegulov** [comment]
@ChaoticTempest agreed, will make a PR that switches the default to an empty byte array shortly and we can go from there

> I also added https://github.com/near/workspaces-rs/pull/83 which propagates these errors a little better than just being ignored

Taking a look right now

**Comment by itegulov** [comment]
> We can try to filter out for certain errors then map them to more intuitive errors later on

We could also easily improve this on the Rust SDK side: just add a check whether the array is empty while the function expect something to deserialize and return a different error message.
