### ISSUE TITLE
Figure out an easy way to both compile contracts and run them with workspaces

### ISSUE THREAD

**Issue by ChaoticTempest** [near/workspaces-rs#54]
This might be a tricky one to solve, but ideally, we should have a way that allows the users of the both the sdk and workspaces to compile a contract, and then automatically point it towards workspaces for it to be deployed. We could scrape the local project's `Cargo.toml` for this info, but there be dragons if it were nested into multiple members.

```rust
worker.dev_deploy(workspaces::this_project());
```
or if multiple contracts
```rust
worker.dev_deploy(workspaces::this_project("ref-finance"));
```
*syntax not final

**Comment by austinabell** [comment]
Don't need to do any scraping I don't think. Can just run a cargo command to compile, maybe the parameter is just to the cargo toml file to use as the `--manifest-path` (or maybe the directory so that we can infer the target directory if we can't pull that) and then maybe have another function or an optional parameter here for a custom target directory (again assuming we might not be able to retrieve the output location and binary name, which might be possible)
