### ISSUE TITLE
how to call a smart contract's method in the same block?

### ISSUE THREAD

**Issue by ChzenChzen** [near/workspaces-rs#93]
I want to test a smart contract's method, and I must be sure that the method execution was made for several accounts in the same block.

**Comment by itegulov** [comment]
https://github.com/near/workspaces-rs/pull/72 is going to add support for batched transactions, so you would be able to ensure that actions are run within the same block. Would that help you with your use case?

**Comment by ChzenChzen** [comment]
@itegulov, for example, I wrote a random number generator and want to ensure that it generates different numbers for different accounts when they call the smart contract method in the same block. If batched, tx can do that so that it will help me.

**Comment by itegulov** [comment]
@ChzenChzen hmm, I don't think your use case can be covered with batch transactions, you would need a way more involved mechanism that can manipulate block production. @ChaoticTempest this might be something to consider for the future.

**Comment by ChaoticTempest** [comment]
AFAIK, normally there's no mechanism that would allow us to schedule a transaction with multiple accounts at the same time, so there wouldn't be a way to test this case for now. Could be a new sandbox feature in the future, but probably not anytime soon since we'd have to go through a lengthy process with adding it to https://github.com/near/nearcore first.


Also you could do batch calls with `accounts` as well, but still wouldn't be what you're looking for, for multiple accounts:
```
let account = worker.dev_create_account().await?;
account
        .batch(&worker, contract.id())
        .call(Function::new("rng").args(vec![]).deposit(0))
        .call(Function::new("rng").args(vec![]).deposit(0))
        .transact()
        .await?;
```
